self.FIREBASE_API_KEY = self.FIREBASE_API_KEY || '';
self.FIREBASE_AUTH_DOMAIN = self.FIREBASE_AUTH_DOMAIN || '';
self.FIREBASE_PROJECT_ID = self.FIREBASE_PROJECT_ID || '';
self.FIREBASE_STORAGE_BUCKET = self.FIREBASE_STORAGE_BUCKET || '';
self.FIREBASE_MESSAGING_SENDER_ID = self.FIREBASE_MESSAGING_SENDER_ID || '';
self.FIREBASE_APP_ID = self.FIREBASE_APP_ID || '';
