// ignore_for_file: avoid_print
//
// Copies GOOGLE_MAPS_API_KEY from ../../.env (repo root) into:
//   - assets/google_maps_platform.env  (Flutter web / dotenv)
//   - ios/Flutter/GoogleMapsEnv.local.xcconfig (iOS build setting override)
//
// Run from the `app/` directory after changing the root .env:
//   dart run tool/sync_google_maps_from_env.dart
//
// Android reads the same root .env at Gradle build time (no sync needed).

import 'dart:io' show Directory, File, Platform, exitCode, stderr;

void main() {
  final appDir = Directory.current;
  if (!File('${appDir.path}${Platform.pathSeparator}pubspec.yaml').existsSync()) {
    stderr.writeln(
      'Run from the app/ directory (pubspec.yaml not found in ${appDir.path}).',
    );
    exitCode = 1;
    return;
  }

  final repoRoot = appDir.parent;
  final envFile = File('${repoRoot.path}${Platform.pathSeparator}.env');
  if (!envFile.existsSync()) {
    stderr.writeln('Missing ${envFile.path}');
    exitCode = 1;
    return;
  }

  final key = _readEnvValue(envFile, 'GOOGLE_MAPS_API_KEY');
  _writeAssetEnv(appDir, key);
  _writeIosXcconfig(appDir, key);
  print('Synced GOOGLE_MAPS_API_KEY into assets/ and ios/Flutter/GoogleMapsEnv.local.xcconfig');
}

String _readEnvValue(File envFile, String name) {
  for (final raw in envFile.readAsLinesSync()) {
    var line = raw.trimRight();
    if (line.isEmpty || line.startsWith('#')) continue;
    final eq = line.indexOf('=');
    if (eq <= 0) continue;
    final k = line.substring(0, eq).trim();
    if (k != name) continue;
    var v = line.substring(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) ||
        (v.startsWith("'") && v.endsWith("'"))) {
      v = v.substring(1, v.length - 1);
    }
    return v;
  }
  return '';
}

void _writeAssetEnv(Directory appDir, String key) {
  final out = File(
    '${appDir.path}${Platform.pathSeparator}assets${Platform.pathSeparator}google_maps_platform.env',
  );
  out.writeAsStringSync(
    '# Generated by tool/sync_google_maps_from_env.dart — do not commit real keys.\n'
    'GOOGLE_MAPS_API_KEY=$key\n',
  );
}

void _writeIosXcconfig(Directory appDir, String key) {
  final safe = key.replaceAll(r'$', r'$$');
  final out = File(
    '${appDir.path}${Platform.pathSeparator}ios${Platform.pathSeparator}Flutter${Platform.pathSeparator}GoogleMapsEnv.local.xcconfig',
  );
  out.writeAsStringSync(
    '// Generated by tool/sync_google_maps_from_env.dart\n'
    'GOOGLE_MAPS_API_KEY=$safe\n',
  );
}
